# -*- mode: ruby -*-
# vi: set ft=ruby :

#

Vagrant.configure('2') do |config|
  ENV['LC_ALL']="en_US.UTF-8"
  config.ssh.insert_key = false

  config.vbguest.auto_update = true

  #vagrant plugin: vagrant-cachier
  config.cache.scope = :box

  config.vm.hostname = 'dev-vm-18.04-bionicbeaver64'
  config.vm.box = "kenrus/ubuntu1804"
#  config.vm.box_version = "1.0.0"

config.vm.provider "virtualbox" do |vb|
  vb.gui = true
  vb.name = 'dev-vm-18.04-bionicbeaver64'
  vb.memory = 10240
  vb.cpus = 6
  vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
  vb.customize ["modifyvm", :id, "--vram", "256"]
  # Enabling the I/O APIC is required for 64-bit guest operating systems, especially Windows Vista;
  # it is also required if you want to use more than one virtual CPU in a VM.
  vb.customize ["modifyvm", :id, "--ioapic", "on"]
  # Enable the use of hardware virtualization extensions (Intel VT-x or AMD-V) in the processor of your host system
  vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
  # Enable, if Guest Additions are installed, whether hardware 3D acceleration should be available
  vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
  vb.customize [ 'modifyvm', :id, '--usbehci', 'off' ]
  vb.customize [ 'modifyvm', :id, '--usb', 'off' ]
  vb.customize [ 'modifyvm', :id, '--audio', 'none' ]
end

# https://itsfoss.com/could-not-get-lock-error/


  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = false
    ansible.compatibility_mode = "2.0"
  end

end
