---
- name: 'Check for tmpDir exists'
  stat: "path={{ tmpDir }}"
  register: p

- name: 'create tmpDir if not exists'
  file:
    path: '{{ tmpDir }}'
    state: directory
  when: not p.stat.exists

- name: "copy default keyboad layout file"
  copy:
    src: '{{ role_path }}/files/keyboard'
    dest: '/etc/default/keyboard'

- name: "copy default locale file"
  copy:
    src: '{{ role_path }}/files/locale'
    dest: '/etc/default/locale'

- name: "set timezone to europe Berlin"
  shell: 'timedatectl set-timezone Europe/Berlin'

# - name: Create a ext4 filesystem on /dev/sdb1 and check disk blocks
#  filesystem:
#    fstype: ext4
#    dev: /dev/sdb
