---

- name: "Add the user {{username}} with a bash shell, appending the group 'users' and 'sudo' to the user's groups"
  user:
    name: "{{username}}"
    shell: /bin/bash
    groups: users,wheel
    append: yes

- name: "set password"
  shell: "usermod --password $(echo \"{{username}}\" | openssl passwd -1 -stdin) {{username}}"

- name: "check local ssh dir exists"
  stat:
    path: '{{localsshdir}}'
  register: ssh_local_exists

- copy:
    src: '{{localsshdir}}'
    dest: '/home/{{username}}'
    group: '{{username}}'
    owner: '{{username}}'
    mode: '700'
  ignore_errors: False
  when: ssh_local_exists.stat.exists == True

- name: "check remote ssh dir exists"
  stat:
    path: '{{localsshdir}}'
  register: ssh_remote_exists

- name: "create dir {{remotesshdir}}"
  file:
    path: '{{remotesshdir}}'
    state: directory
    group: '{{username}}'
    owner: '{{username}}'
    mode: u=rwx,g=rwx,o=rwx
    recurse: yes
  when: ssh_remote_exists.stat.exists == False

- name: 'add config file to folder {{remotesshdir}}'
  template:
    src: 'config.j2'
    dest: '{{remotesshdir}}/config'
    mode: '700'
  when: ssh_remote_exists.stat.exists == False

- name: 'Recursively change ownership of a {{remotesshdir}}'
  file:
    path: '{{remotesshdir}}'
    state: directory
    recurse: yes
    owner: '{{username}}'
    group: '{{username}}'
    mode: '700'

- name: "create Desktop dir"
  file:
    path: '/home/{{username}}/Desktop'
    state: directory
    owner: '{{username}}'
    group: users
    mode: '755'

- name: 'copy gitconfig'
  template:
    src: 'gitconfig.j2'
    dest: '/home/{{username}}/.gitconfig'
    owner: '{{username}}'
    group: '{{username}}'
    mode: '740'

- name: "add alias gs to bashrc"
  shell: |
    if ! grep -Fq "alias gs=" {{bashrc_file}}; then
      echo "alias gs=\"git status\"" >> {{bashrc_file}}
    fi

- name: "add alias gc to bashrc"
  shell: |
    if ! grep -Fq "alias gc=" {{bashrc_file}}; then
      echo "alias gc=\"git clone\"" >> {{bashrc_file}}
    fi

- name: "add alias gf to bashrc"
  shell: |
    if ! grep -Fq "alias gf=" {{bashrc_file}}; then
      echo "alias gf=\"git fetch\"" >> {{bashrc_file}}
    fi

- name: "add alias gp to bashrc"
  shell: |
    if ! grep -Fq "alias gp=" {{bashrc_file}}; then
      echo "alias gp=\"git pull\"" >> {{bashrc_file}}
    fi

- name: "add alias gfp to bashrc"
  shell: |
    if ! grep -Fq "alias gfp=" {{bashrc_file}}; then
      echo "alias gfp=\"git fetch && git pull\"" >> {{bashrc_file}}
    fi

- name: "add alias gl to bashrc"
  shell: |
    if ! grep -Fq "alias gl=" {{bashrc_file}}; then
      echo "alias gl=\"git log --oneline\"" >> {{bashrc_file}}
    fi
