---
- hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars/common.yml
  vars:

  roles:
    - role: prepare

    - role: user

    - role: geerlingguy.mysql
      mysql_root_username: 'root'
      mysql_root_password: 'nova1234-'

    - role: geerlingguy.docker
      docker_edition: 'ce'
      docker_package_state: latest
      docker_install_compose: true

    - role: gantsign.java
      java_version: '14'
      java_is_default_installation: no
      java_fact_group_name: java_14

    - role: gantsign.java
      java_version: '11'
      java_is_default_installation: yes
      java_fact_group_name: java

    - role: gantsign.maven

    - role: gantsign.intellij

    - role: gantsign.visual-studio-code
      users:
        - username: arl
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - vscjava.vscode-java-pack
            - redhat.vscode-quarkus
            - richardwillis.vscode-gradle
            - donjayamanne.git-extension-pack

    - role: shelleg.gradle
      environment:
        JAVA_HOME: "{{ ansible_facts['ansible_local']['java']['general']['home'] }}"
      gradle_version: 6.3
      gradle_checksum: sha256:0f316a67b971b7b571dac7215dcf2591a30994b3450e0629925ffcfe2c68cc5c
      gradle_base_dir: /opt

    - role: devoinc.ansible_graalvm_ce