---
- hosts: all
  gather_facts: true
  become: yes
  vars_files:
    - vars/common.yml
  vars:

  roles:
    - role: prepare

    - name: geerlingguy.mysql
      mysql_root_username: 'root'
      mysql_root_password: 'nova1234-'
      mysql_python_package_debian: 'python3-mysqldb'

    - role: geerlingguy.docker
      docker_edition: 'ce'
      docker_package_state: latest
      docker_install_compose: true

    - role: user

    - role: gantsign.java
      java_version: '14'
      java_is_default_installation: no
      java_fact_group_name: java_14

    - role: gantsign.java
      java_version: '8'
      java_is_default_installation: no
      java_fact_group_name: java_8

    - role: gantsign.java
      java_version: '11'
      java_is_default_installation: yes
      java_fact_group_name: java

    - role: gantsign.maven

    - role: gantsign.intellij
      intellij_default_maven_home: '/opt/maven/apache-maven-3.6.3'
      users:
        - username: arl
          intellij_jdks:
            - name: '8'
              home: '/opt/java/jdk8u252'
            - name: '11'
              home: '/opt/java/jdk-11.0.7'
            - name: '14'
              home: '/opt/java/jdk-14.0.1'
          intellij_default_jdk: '11'
          intellij_codestyles:
            - name: GoogleStyle
              url: 'https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml'
          intellij_default_codestyle: GoogleStyle
          intellij_plugins:
            - CheckStyle-IDEA
            - DBN
            - Key Promoter X
            - org.jetbrains.kotlin

    - role: gantsign.visual-studio-code
      users:
        - username: arl
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - vscjava.vscode-java-pack
            - redhat.vscode-quarkus
            - richardwillis.vscode-gradle
            - donjayamanne.git-extension-pack

    - role: shelleg.gradle
      environment:
        JAVA_HOME: "{{ ansible_facts['ansible_local']['java']['general']['home'] }}"
      gradle_version: 6.3
      gradle_checksum: sha256:0f316a67b971b7b571dac7215dcf2591a30994b3450e0629925ffcfe2c68cc5c
      gradle_base_dir: /opt

#    - role: devoinc.ansible_graalvm_ce

    - role: gantsign.minikube

    - role: andrewrothstein.kubectl
      kubectl_ver: v1.17.4

    - role: gantsign.postman

    - role: arolfes.soapui

    - role: arolfes.graalvm
      graalvm_java_version: '8'
      graalvm_is_default_installation: false
      graalvm_fact_group_name: 'graalvm-java8'

    - role: arolfes.graalvm
      # with this option jdk 11 is still in path and not overruled by graalvm
      # bash> java --version # shows jdk 11 from openjdk and not graalvm
      graalvm_add_to_path: false
