---
- name: "check if new swap file exits"
  stat:
    path: /swapfile_{{swap_file_size}}.img
  register: p

- name: "Greet the world if /etc/fstab contains swapfile_{{swap_file_size}}.img"
  debug: msg="Hello, world! {{p}}"
  
- name: "increase the swapfile size"
  shell: 'touch {{swap_file}} && fallocate -l {{swap_file_size}} {{swap_file}} && mkswap {{swap_file}} && swapon -p 20 {{swap_file}}'
  when: p.stat.exists == False
  
- name: "comment out exisitng swap file in /etc/fstab"
  lineinfile:
    dest: /etc/fstab
    line: "#/swapfile                                 none            swap    sw              0       0"
    regexp: "/swapfile"
    state: present
  when: p.stat.exists == False

- name: "add new swapfile to /etc/fstab"
  lineinfile:
    dest: /etc/fstab
    line: "/swapfile_{{swap_file_size}}.img                                 none            swap    sw,prio=20              0       0"
    regexp: "/swapfile_{{swap_file_size}}.img"
    state: present
    insertafter: EOF
  when: p.stat.exists == False
