---

- name: "copy resolv.conf to /run/systemd/resolve/resolv.conf"
  copy:
    src: '{{ role_path }}/files/resolv.conf'
    dest: '/run/systemd/resolve/resolv.conf'

- name: "delete /etc/resolv.conf"
  file:
    state: absent
    path: '/etc/resolv.conf'
  ignore_errors: True

- name: "symlink /run/systemd/resolve/resolv.conf -> /etc/resolv.conf"
  file:
    src: '/run/systemd/resolve/resolv.conf'
    dest: '/etc/resolv.conf'
    state: link

- name: "sysctl vm.max_map_count=262144"
  shell: 'sysctl -w vm.max_map_count=262144'

- name: "sysctl fs.file-max=65536"
  shell: 'sysctl -w fs.file-max=65536'

- name: "ulimit -n 65536"
  shell: 'ulimit -n 65536'
